# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Copper_Math_config = debug

else ifeq ($(config),release)
  Copper_Math_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Copper-Math

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Copper-Math:
ifneq (,$(Copper_Math_config))
	@echo "==== Building Copper-Math ($(Copper_Math_config)) ===="
	@${MAKE} --no-print-directory -C CMath -f Makefile config=$(Copper_Math_config)
endif

clean:
	@${MAKE} --no-print-directory -C CMath -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Copper-Math"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"